### ISSUE TITLE
nRF51 SWD no response

### ISSUE THREAD

**Issue by mobier** [szymonh/SWDenum#1]
![](https://file-temp.oss-cn-beijing.aliyuncs.com/20200420191838.png)

Normal recognizable device (nrf51822)

![](https://file-temp.oss-cn-beijing.aliyuncs.com/20200420191849.png)

Use logic analyzer to resolve to device ID (0xbb11477)

![](https://file-temp.oss-cn-beijing.aliyuncs.com/20200420191902.png)

Using Arduino uno / micro (16mhz) does not show back

![](https://file-temp.oss-cn-beijing.aliyuncs.com/20200420191910.png)

Device reply noreply

![](https://file-temp.oss-cn-beijing.aliyuncs.com/20200420191924.png)

Waveform when disconnecting from nrf51 cable

**Comment by szymonh** [comment]
Hi @mobier, thanks for trying out the app, hopefully I'll be able to resolve the issue.

Could you please let me understand the situation a bit better by answering the below questions?

1. Looking at the issue report you mentioned use of Arduino Uno and Micro 16Mhz which both use 5V level logic, while the nRF51 uses 3.3V logic. Have you included a level shifter between your 5V Arduino and the 3.3V nRF51?

2. I understand that the nRF SWDCLK is connected to GPIO PIN 2, SWDIO to GPIO PIN 3 (both through a logic level shifter if using a 5V Arduino) and GND is connected between Arduino and the target. Is this correct? 

3. Are the screenshots from logic analyzer complete? Looking at the image the switch from jtag to swd is missing. Perhaps you could export and attach the logic analyzer capture to this issue if it's not very large? 

Thanks for your input.

Best regards,
Szymon

**Comment by szymonh** [comment]
@mobier Could you please provide some more information by answering earlier questions?
