### ISSUE TITLE
Nothing detected on Pi Pico

### ISSUE THREAD

**Issue by SheetLightning** [szymonh/SWDenum#2]
Thank you for making the project available, however, it would not detect the SWD pins on a Raspberry Pico for some reason. I used pins 2 - 7 on an Arduino Leonardo with pin mask 0xFC and connected any two pins at random to the Pico. Since the Leonardo outputs at 5V, a level shifter was used between the Leonardo and the Pico. GND was connected between the two boards via the level shifter and also, for good measure, via a separate GND to GND wire. The program just returned '---- FAILURE ----' for both enumeration mode and when testing specific pins. I was able to verify that something was being transmitted from the Arduino to the Pico by probing both Arduino GPIO pins and the SWDIO pin on the Pico with an oscilloscope. The signal was clearly visible at 5V on the Arduino pins as well as at 3.3V on the Pico side of the level shifter.

I was able to verify SWD operation of both my Pico boards by building and testing the Picoprobe project from Raspberry. This worked fine and I was able to use Picoprobe installed on one Pico board to upload and debug code on the other Pico board. This tests shows that SWD communication is working on both boards.

**Comment by szymonh** [comment]
As a first guess I would expect the level shifter to be the culprit. Could you verify that by using two Pico boards so both app and target use same voltage level? An Arduino core for Pico is available.

**Comment by Twilight-Logic** [comment]
Should have thought to do that myself! Ok, I set up the IDE for Pico. Adeed the following to the Additional boards manager URLs in  Preferences:

https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

I was able then to select the Raspberry Pico board in the IDE. I compiled and exported the binaries and then put the board in BOOTSEL mode and copied the UF2 file to it. The two boards were connected like this:

SWDscan - DUT
-------------------
GND -> GND
GP2 -> SWDIO
GP3 -> SWDCLK

The mask was set to 0x0C (to enable only pins GP2 and GP3). The result was unfortunately the same.

```
> e
+-------------------------------------------+
| CLK PIN | IO PIN | ACK | PART NO | MAN ID |
+-------------------------------------------+
|    2    |    3   |  7  |   ffff  |   7ff  |
|    3    |    2   |  7  |   ffff  |   7ff  |
+----------------- FAILURE -----------------+
> t
Enter SWD CLK PIN NO 3
Enter SWD IO PIN NO 2
+-------------------------------------------+
| CLK PIN | IO PIN | ACK | PART NO | MAN ID |
+-------------------------------------------+
|    3    |    2   |  7  |   ffff  |   7ff  |
+----------------- FAILURE -----------------+
>
```

**Comment by SheetLightning** [comment]
Thanks for your reply. I should have thought to do that myself! As per your request I set up the IDE for compiling to a Pico board. The following URL was added to the Additional boards manager URLs in Preferences:

`https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json`

The 'Raspberry Pi Pico' board then became available in Boards Manager. This was selected, the SWDscan sketch compiled and the binaries exported. The board was then put in BOOTSEL mode and the uf2 file copied to it. The Pico was then power cycled and tested. SWDscan responded on /dev/ttyACM0 as expected.

The two boards were then connected together like this:

<table>
<tr>
	<th>SWDscan
	<th>DUT
<tr>
	<td>GND
	<td>GND
<tr>
	<td>GP2
	<td>SWDIO
<tr>
	<td>GP3
	<td>SWDCLK
</table>


The mask was set to 0x0C (to enable only pins GP2 and GP3). The result was unfortunately the same.

```
> e
+-------------------------------------------+
| CLK PIN | IO PIN | ACK | PART NO | MAN ID |
+-------------------------------------------+
|    2    |    3   |  7  |   ffff  |   7ff  |
|    3    |    2   |  7  |   ffff  |   7ff  |
+----------------- FAILURE -----------------+
> t
Enter SWD CLK PIN NO 3
Enter SWD IO PIN NO 2
+-------------------------------------------+
| CLK PIN | IO PIN | ACK | PART NO | MAN ID |
+-------------------------------------------+
|    3    |    2   |  7  |   ffff  |   7ff  |
+----------------- FAILURE -----------------+
>
```

**Comment by szymonh** [comment]
Thanks for checking that out. 
I'll organize a Pico and get back to you in a few days, once I receive the hardware.

**Comment by SheetLightning** [comment]
Thank you. I just also checked on the oscilloscope to make sure that something was happening on GP2 and GP3 and I do see pulses during the enumeration on both pins.

**Comment by szymonh** [comment]
Looks like that RP2040 is using SWD "v2" with multi-drop support so the initialization phase is different than in case of "classic" SWD thus pin identification fails.

**Comment by szymonh** [comment]
@SheetLightning can you please retry with latest changes?

**Comment by SheetLightning** [comment]
Yes, that seems to work! Thank you.

I tried it with the scanner running on the Pico and then also on the Arduino Leonardo connected via the level shifter. Both worked.

Does it automatically switch between v1 and v2 protocols?

**Comment by szymonh** [comment]
Great, thanks a lot you for verification and brinding this to my attention.

I checked the documentation for ARM [debug interface](https://documentation-service.arm.com/static/5f900b6cf86e16515cdc0648) and figured out that chips with SWD newer than v1 have a more complex state machine and dormant state needs to be left prior to retrieval of the ID Code (section B5.3.4 of the manual). So to make things as simple as possible the execution flow is always the same despite of target SWD version - in case of v1 chips the leave dormant state sequence will simply be ignored as unknown allowing detection of different revisions.
